#!/bin/sh

echo "Running apt update..."
sudo apt update > /tmp/apt_update
echo "Runninng apt upgrade..."
sudo apt upgrade -y > /tmp/apt_upgrade

echo "Adding Azure_DevOps User..."
adduser --quiet --disabled-password --shell /bin/bash --home /home/azure_devops --gecos "Azure Agent DevOps" azure_devops
echo "Adding Azure_DevOps user to sudoers..."
echo -e 'azure_devops\tALL=(ALL)\tNOPASSWD:\tALL' > /etc/sudoers.d/azure_devops

mkdir /home/azure_devops/.ssh
chown azure_devops.azure_devops /home/azure_devops/.ssh
chmod 700 /home/azure_devops/.ssh

PUBKEY="ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQChc9caNJhx0r9UMZ852/guT2x/4saBDAEJ7I1cbUHj9nNjRMW5vDbuidEYG7T+JxTFmftJTxIburQHT0MPjaevm9HLwVvIavjWMfVTmMes3/ZfQEtP/TmK9vKqyx6qkhmwD9GLwxY8AmeJARjREGEBDc1iGvwPqvOgaAjwy4f6XF5gIyxKN3FTMa6YVKRXxtSvX93QC3GcNecuF5/B3ANRJuy0FWDOG0JuTON8mj61QUnIFbtTv5aZ7s5fKHx5LM+c18Gdmd9ctb3uLBCtOmla8OWKtVgDOQ9Bx7PCJwjDWkXfuSv6zaNyHLWVXQKAx6xLKgJZzPnhjUH0T/mB6Wm32G8fnNzhBXLPxSsl+U6yq4pisRngy1eNejgtWJX6ho6QehNSdvsIRykUGNyFNLV4sLsnOd++MkwAmp/E6PjYsWDhmP2/ufgFsH0xLcFVDoJ73LVHZVCHzo3thEnv+8+e5kZd0JLOJlzDHvWT9M4ZI0tlUXh4gTn+9J4bU964OkFb1dEz/lG9vrpixy38wEVIw1L/Ru7AHFVkJxTdAN3jDREx7d8FdIv39BzlCS/7UKUtLfnMv2pyz8nItclq/D4yoJxCV0c+GRUQIiuIEm4btXM4o+WgryjIJkOd4LWpDvbf2l8TZGvg7tjFwMIWHSQpFHGvbcpHdbNyre/GNuV4MQ== Generated by Azure."
echo ${PUBKEY} > /home/azure_devops/.ssh/id_rsa.pub
chown azure_devops.azure_devops /home/azure_devops/.ssh/id_rsa.pub
chmod 644 /home/azure_devops/.ssh/id_rsa.pub
